# Generated by Django 4.2 on 2023-05-11 14:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
