# Generated by Django 4.2 on 2023-05-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_featured_featuredarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='featured',
        ),
    ]
