# Generated by Django 4.2 on 2023-07-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0005_document_subcategory_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='group',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='group',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
