# Generated by Django 4.2 on 2023-07-02 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_subcategory_group_subcategory_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.subcategory'),
        ),
    ]
