# Generated by Django 4.2 on 2023-07-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0007_alter_document_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='group',
            new_name='groups',
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
