# Generated by Django 4.2 on 2023-07-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_rename_group_subcategory_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='document',
            name='subcategory',
            field=models.ManyToManyField(blank=True, related_name='documents', to='documents.subcategory'),
        ),
    ]
