# Generated by Django 4.2 on 2023-07-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_document_author_alter_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='subcategory',
            field=models.ManyToManyField(null=True, related_name='documents', to='documents.subcategory'),
        ),
    ]
