# Generated by Django 4.2 on 2023-07-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0012_alter_document_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
